### PR TITLE
Remove du

### PR DESCRIPTION
**Pull request by BridgeAR**
This improves the performance significantly by removing du. Instead
of calculating the size upfront and then calculating it again later,
it just stats each file that will be removed. That combined is
almost the identical information as before but in significantly less
time.

Please note: in a brief test this did not yield the exact same size diff.
I am pretty confident that my logic is correct though and this should work.

### CODE REVIEW

**Comment by Trott** [comment]
This removes some functionality in that it no longer reports the percentage decrease in size. That's not necessarily a deal-breaker, but worth considering.

**Comment by Trott** [comment]
(I wonder if there's room for a CLI flag here to specify that you want stuff to be fast, and it just doesn't bother with reporting on size, etc.)

**Comment by BridgeAR** [comment]
It is also possible to keep this 100% functional and still to improve the performance by a) only checking the total folder size up front and to subtract the rest later on. The benefit would be significantly smaller though.

Another improvement would be to use the new Node.js readdir option that allows to read the stats as well. That would be significantly faster while still a bit more work and there's no module doing that right now (especially, since it requires feature detection and a fallback mode for versions not supporting the feature).

This could just be released as semver-major. I don't think the percentage is critical.

Adding a flag would also be possible. That way it would only be semver-minor instead of mayor. We could even allow to skip the size completely (I personally am fine with the number of files being removed).

@inikulin thoughts?

**Comment by Trott** [comment]
Thinking more about it, I think this is fine the way it is.

**Comment by Trott** [comment]
@BridgeAR Would you be up for adding a test? Just something that checks that some number is contained in the output and that the number is in a reasonably expected format?

**Comment by BridgeAR** [comment]
Sure, done!

**Pull request merged**
